name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Start Telegraf
      run: |
        docker run -d \
          --name telegraf \
          -p 8089:8089/udp \
          -v ${{ github.workspace }}/telegraf.conf:/etc/telegraf/telegraf.conf \
          telegraf:latest
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Setup Environment and Install Dependencies
      run: |
        uv venv
        uv pip install maturin pytest
        uv sync
    
    - name: Build and Install extension
      env:
        PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
      run: |
        uv run maturin build --release
        uv pip install target/wheels/*.whl
    
    - name: Run tests
      run: |
        sleep 5
        uv run pytest
      env:
        TELEGRAF_URL: udp://localhost:8089

    - name: Check Telegraf Logs (if failed)
      if: failure()
      run: docker logs telegraf

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: target/wheels/*.whl